version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: solnet_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solnet
      MYSQL_USER: solnet
      MYSQL_PASSWORD: solnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

  adminer:
    image: adminer:latest
    container_name: solnet_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build:
      context: ./api
    #   dockerfile: dockerfile   # (opcional; si tu archivo se llama exactamente 'dockerfile', dejalo)
    container_name: solnet_api
    env_file:
      - ./api/.env
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

volumes:
  db_data: