version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solnetcrm
      MYSQL_USER: solnet
      MYSQL_PASSWORD: solnet
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app

volumes:
  dbdata:
