version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: solnet-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solnetcrm
      MYSQL_USER: solnet
      MYSQL_PASSWORD: solnet
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: solnet-backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "mysql://solnet:solnet@db:3306/solnetcrm"
    ports:
      - "3000:3000"
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: solnet-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  dbdata:
